### ISSUE TITLE
Allow a user to request a password reset

### ISSUE THREAD

**Issue by jmfernandez** [inab/rd-connect-user-management-interface#3]
Currently, if a user lose her/his password, (s)he cannot request in an automated way a password reset.

**Comment by dpiscia** [comment]
How is going this JM?

**Comment by jmfernandez** [comment]
I'm still on it, a paper submission kept me very busy the whole past week

**Comment by jmfernandez** [comment]
This issue depends on issue inab/rd-connect-user-management#4

**Comment by jmfernandez** [comment]
This enhancement was properly implemented in a sister repo: https://github.com/inab/rd-connect-requests-interface
